#!/usr/bin/env bash
# title          :rpn.sh
# description    :A Reverse Polish Notation calculator
# author         :Timothy Merritt
# date           :2020-11-17
# version        :0.1.0
# usage          :./rpn.sh
# bash_version   :5.0.18(1)-release
#============================================================================

# TODO:
# * help text
# * getopts
# * round
# * binary
# * factorial
# * move
# * swap
# * drop
# * dupl
# * sqrt
# * pi
# ----------------
# * customizations

set -e
set -u
set -o pipefail

source ./INFO
source ./.rpnrc

function is_number() {
  # Trim leading and extranneous 0s
  strip="${1#"${1%%[!0]*}"}"
  if [[ "${strip}" =~ "0" ]]; then
    shift
  fi &&
    if [[ "${strip}" =~ $num ]]; then
      STACK+=("${strip}") || STACK+=("${1}")
      shift
    fi
}

function calc() {
  op=$1
  int_1=${STACK[0]}
  int_2=${STACK[1]}
  # ++ & -- should not replace first two digits, only first
  if [ "$op" = "^" ]; then
    op="*"
  elif [ "$op" = "++" ]; then
    op="+"
    int_2="1"
  elif [ "$op" = "--" ]; then
    op="-"
    int_2="1"
  fi
  result=$(echo "${int_1} $op ${int_2}" | bc -l 2>/dev/null | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
  STACK=("${STACK[@]:2}")
  STACK=($result "${STACK[@]}")
}

function check_stack() {
  if [ "${#STACK[@]}" -lt "2" ] && [ "$1" != "++" ] && [ "$1" != "--" ]; then
    echo -e "${RED}𐄂 ERROR${BASE}: ${key} cannot be performed on a single number."
    echo "  Enter more numbers to calculate, or use a valid unary operator. "
    echo "  Type 'help' or 'usage' for more information."
    echo
  else
    calc "$key"
  fi
}

function clear_stack() {
  unset STACK
}

function parse_input() {
  while [[ "$#" -gt 0 ]]; do
    key="$1"
    is_number "$1"
    case $key in
    "q" | "Q" | "quit" | "exit")
      exit
      ;;
    "swap")
      temp="${STACK[0]}"
      temp2="${STACK[1]}"
      STACK=("${STACK[@]:2}")
      STACK=(${STACK[@]:0:0} $temp ${STACK[@]:0})
      STACK=(${STACK[@]:0:0} $temp2 ${STACK[@]:0})
      shift
      ;;
    "fac")
      factorial=1
      for ((i = 1; i <= "${STACK[0]}"; i++)); do
        factorial=$(($factorial * $i))
      done
      STACK=("${STACK[@]:1}")
      STACK=(${STACK[@]:0:0} $factorial ${STACK[@]:0})
      shift
      ;;
    "drop")
      STACK=("${STACK[@]:1}")
      shift
      ;;
    "bin")
      binary=$(echo "obase=2;${STACK[0]}" | bc)
      STACK=("${STACK[@]:1}")
      STACK=($binary "${STACK[@]}")
      shift
      ;;
    "dec")
      decimal=$(echo "ibase=2;${STACK[0]}" | bc)
      STACK=("${STACK[@]:2}")
      STACK=($decimal "${STACK[@]}")
      shift
      ;;
    "usage")
      usage
      shift
      ;;
    "v" | "-v" | "--version" | "version")
      version
      shift
      ;;
    "clr")
      clear_stack
      shift
      ;;
    "+" | "-" | "^" | "/" | "%")
      check_stack
      shift
      ;;
    "++" | "--")
      check_stack "$key"
      shift
      ;;
    "help")
      less ./HELP
      shift
      ;;
    *)
      shift
      ;;
    esac
  done
}

function rpn() {
  # For piped input
  if [ -p /dev/stdin ]; then
    while read piped; do
      parse_input $piped && echo -e "${STACK[@]}"
    done
  else
    # For arguments
    for i in $@; do
      # read $i
      parse_input $i
    done
    # For regular usage
    echo -en "${STACK[@]}" "> "
    while read INPUT; do
      parse_input $INPUT && echo -en "${STACK[@]}" "> "
    done
  fi
}

rpn $@
